<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>.GlobalPreferences</key>
<dict>
	<key>AppleShowAllExtensions</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>MultipleSessionEnabled</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<false/>
	</dict>
	<key>com.apple.autologout.AutoLogOutDelay</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<integer>0</integer>
	</dict>
</dict>
<key>com.apple.MCX</key>
<dict>
	<key>DisableGuestAccount</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>com.apple.EnergySaver-ShowMenuBarBattery</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>com.apple.EnergySaver.portable.ACPower-ProfileNumber</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<integer>4</integer>
	</dict>
	<key>com.apple.EnergySaver.portable.ACPower-raw</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>upk</key>
		<dict>
			<key>mcx_input_key_names</key>
			<array>
				<string>com.apple.EnergySaver.portable.ACPower-raw</string>
			</array>
			<key>mcx_output_key_name</key>
			<string>com.apple.EnergySaver.portable.ACPower</string>
			<key>mcx_remove_duplicates</key>
			<true/>
			<key>mcx_union_as_dictionary</key>
			<true/>
		</dict>
		<key>value</key>
		<dict>
			<key>Automatic Restart On Power Loss</key>
			<integer>0</integer>
			<key>Disk Sleep Timer-boolean</key>
			<true/>
			<key>Display Sleep Timer</key>
			<integer>5</integer>
			<key>Dynamic Power Step</key>
			<integer>0</integer>
			<key>Reduce Processor Speed</key>
			<integer>0</integer>
			<key>System Sleep Timer</key>
			<integer>10</integer>
			<key>Wake On LAN</key>
			<integer>1</integer>
			<key>Wake On Modem Ring</key>
			<integer>0</integer>
		</dict>
	</dict>
	<key>com.apple.EnergySaver.portable.BatteryPower-ProfileNumber</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<integer>-1</integer>
	</dict>
	<key>com.apple.EnergySaver.portable.BatteryPower-raw</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>upk</key>
		<dict>
			<key>mcx_input_key_names</key>
			<array>
				<string>com.apple.EnergySaver.portable.BatteryPower-raw</string>
			</array>
			<key>mcx_output_key_name</key>
			<string>com.apple.EnergySaver.portable.BatteryPower</string>
			<key>mcx_remove_duplicates</key>
			<true/>
			<key>mcx_union_as_dictionary</key>
			<true/>
		</dict>
		<key>value</key>
		<dict>
			<key>Automatic Restart On Power Loss</key>
			<integer>0</integer>
			<key>Disk Sleep Timer-boolean</key>
			<true/>
			<key>Display Sleep Timer</key>
			<integer>9</integer>
			<key>Dynamic Power Step</key>
			<integer>1</integer>
			<key>Reduce Processor Speed</key>
			<integer>0</integer>
			<key>System Sleep Timer</key>
			<integer>15</integer>
			<key>Wake On LAN</key>
			<integer>0</integer>
			<key>Wake On Modem Ring</key>
			<integer>0</integer>
		</dict>
	</dict>
</dict>
<key>com.apple.SoftwareUpdate</key>
<dict>
	<key>CatalogURL</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<string>http://ellipse.adullmoment.com:8088/index.sucatalog</string>
	</dict>
</dict>
<key>com.apple.finder</key>
<dict>
	<key>AppleShowAllExtensions-immutable</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>FinderSpawnWindow</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>FinderSpawnWindow-immutable</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>InterfaceLevel</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<string>Full</string>
	</dict>
	<key>NewWindowTargetIsHome</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>NewWindowTargetIsHome-immutable</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>OpenInColumnView</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<false/>
	</dict>
	<key>OpenInColumnView-immutable</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>ShowExternalHardDrivesOnDesktop</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>ShowExternalHardDrivesOnDesktop-immutable</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>ShowHardDrivesOnDesktop</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>ShowHardDrivesOnDesktop-immutable</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>ShowMountedServersOnDesktop</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>ShowMountedServersOnDesktop-immutable</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>ShowRemovableMediaOnDesktop</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>ShowRemovableMediaOnDesktop-immutable</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>WarnOnEmptyTrash</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>WarnOnEmptyTrash-immutable</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
</dict>
<key>com.apple.loginwindow</key>
<dict>
	<key>AdminHostInfo</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<string>HostName</string>
	</dict>
	<key>AdminMayDisableMCX</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>DisableConsoleAccess</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>EnableExternalAccounts</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>HideAdminUsers</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<false/>
	</dict>
	<key>HideLocalUsers</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<false/>
	</dict>
	<key>HideMobileAccounts</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<false/>
	</dict>
	<key>IncludeNetworkUser</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<false/>
	</dict>
	<key>LoginwindowText</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<string>This is a machine.</string>
	</dict>
	<key>RestartDisabled</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<false/>
	</dict>
	<key>RetriesUntilHint</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<integer>3</integer>
	</dict>
	<key>SHOWFULLNAME</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>SHOWOTHERUSERS_MANAGED</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>ShutDownDisabled</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<false/>
	</dict>
	<key>UseComputerNameForComputerRecordName</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>com.apple.login.mcx.DisableAutoLoginClient</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
	<key>mcx_UseLoginWindowText</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<true/>
	</dict>
</dict>
<key>com.apple.screensaver</key>
<dict>
	<key>loginWindowIdleTime</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<integer>900</integer>
	</dict>
	<key>loginWindowModulePath</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<string>/System/Library/Screen Savers/Flurry.saver</string>
	</dict>
</dict>
<key>com.apple.systempreferences</key>
<dict>
	<key>com.apple.preferences.users</key>
	<dict>
		<key>state</key>
		<string>always</string>
		<key>value</key>
		<array>
			<string>MultipleSessionEnabled</string>
		</array>
	</dict>
</dict>
</dict>
</plist>